[package]
name = "project_name" # replace per repo
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.0"
openzeppelin = "2.0.0"

[dev-dependencies]
snforge_std = "0.49.0"

[scripts]
test = "snforge test"

[lib]

[[target.starknet-contract]]

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[[tool.snforge.fork]]
name = "MAINNET_LATEST"
url = "REPLACE_WITH_RPC_URL"
block_id.tag = "latest"

[[test]]
name = "contracts_unittest"
