[package]
name = "project_name" # replace per repo
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.0"

[dev-dependencies]
snforge_std = "0.51.1"
assert_macros = "2.15.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.fmt]
sort-module-level-items = true

# Uncomment for coverage support:
# [profile.dev.cairo]
# unstable-add-statements-code-locations-debug-info = true
# unstable-add-statements-functions-debug-info = true
# inlining-strategy = "avoid"
